### ISSUE TITLE
README.md doesn't scroll

### ISSUE THREAD

**Issue by drmikecrowe** [kaleguy/leovue#2]
You can't scroll long pages:  [README.md](https://kaleguy.github.io/leovue/#/t/10/)

**Comment by kaleguy** [comment]
How are you viewing the README.md? I don't see any scroll issues. Are you viewing with Leo Vue? If so, send url.

**Comment by kaleguy** [comment]
Oh didn't realize that had a link. Just checked it on Windows and Mac in Chrome. Only Chrome is supported. Are you seeing the problem in Chrome?

**Comment by drmikecrowe** [comment]
Yep, I'm serving it locally, if that makes a difference.

What seems to solve the problem are these style changes:
```css
  .right-cpane {
    flex: auto;
    background: #fff;
    padding: 0px;
    // padding-top: 33px;
    // max-width: 620px;
    // width: 620px;
    // min-width: 500px;
    // height: calc(100vh - 33px);
    overflow: auto;
  }
```
